name: Update README

on:
  push:
  schedule: 
   - cron: '0 12 * * *'
   
jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install praw
          pip install python-dotenv

      - name: Run Python script
        run: python updater.py
        
      - name: Update GitHub Profile README
        uses: theboi/github-update-readme@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: 'post.txt'
          replace: '<!-- top-post -->'
